fragment JobResult on JobRun {
  id
  state
}

query GetProject($path: String!) {
  project(path: $path) {
    id
  }
}

mutation RunJob($input: RunJobInput!) {
  runJob(input: $input) {
    id
    ...JobResult
  }
}

query GetJob($repo: ID!, $job: UUID!) {
  currentUser {
    id
    repo(id: $repo) {
      id
      jobRun(id: $job) {
        id
        ...JobResult
      }
    }
  }
}
